name: Pipeline

run-name: Run triggered by ${{ github.actor }}

on: [push]

jobs:
  build:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: /home/actions-runner/dotnet
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
      - name: Build projects
        run: |
          dotnet build NextStop/NextStop.Dal.Common
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            **/bin/
            **/obj/

  test:
    runs-on: self-hosted
    needs: build
    env:
      DOTNET_INSTALL_DIR: /home/actions-runner/dotnet
      NUGET_PACKAGES: /home/actions-runner/.nuget/packages
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
      - name: Install dependencies
        run: dotnet restore NextStop/NextStop.Tests
      - name: Test projects
        run: dotnet test --no-restore NextStop/NextStop.Tests
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            **/bin/
            **/obj/
