name: Build

on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    defaults:
      run:
        working-directory: "NextStop"
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build NextStop.Dal.Common
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: | 
            **/bin/
            **/obj/
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    defaults:
      run:
        working-directory: "NextStop"
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            **/bin/
            **/obj/
